# .cpanel.yml - DIAGNOSTIC VERSION
deployment:
  tasks:
    - export DEPLOYPATH=/home/nexuseng/public_html
    - echo "--- Starting diagnostic deployment ---"
    - set -e # Exit immediately if any command fails

    # 1. Check the environment
    - echo "--- Checking environment ---"
    - echo "User: $(whoami)"
    - echo "Path: $PATH"
    - echo "Node version:"
    - node -v || echo "Node command not found"
    - echo "NPM version:"
    - npm -v || echo "NPM command not found"

    # 2. Install and build
    - echo "--- Installing dependencies ---"
    - npm install
    - echo "--- Building Astro site ---"
    - npm run build

    # 3. Verify build output
    - echo "--- Verifying build output in 'dist' directory ---"
    - ls -la dist

    # 4. Deploy files
    - echo "--- Deploying 'dist' contents to $DEPLOYPATH ---"
    - /bin/cp -a dist/. $DEPLOYPATH
    - echo "--- Deploying .htaccess ---"
    - /bin/cp .htaccess.astro $DEPLOYPATH/.htaccess
    - echo "--- Deployment finished successfully ---"