# .cpanel.yml
deployment:
  tasks:
    - export DEPLOYPATH=/home/nexuseng/public_html
    # 1. Build the Astro site
    - npm install
    - npm run build
    # 2. Deploy the contents of the 'dist' folder
    - /bin/cp -R dist/* $DEPLOYPATH
    # 3. Deploy the Astro-specific .htaccess
    - /bin/cp .htaccess.astro $DEPLOYPATH/.htaccess
