deployment:
  tasks:
    - export DEPLOYPATH=/home/nexuseng/public_html
    - /bin/cp -R index.html about.html contact.html services.html insights.html thank-you.html sendmail.php css images js jobposts header.html footer.html .htaccess robots.txt sitemap.xml careers.html $DEPLOYPATH
