name: Generate Job Pages

on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (if needed)
        run: npm ci || true

      - name: Run job page generator
        run: node js/generateJobPages.js

      - name: Commit and push generated job pages
        run: |
          git config user.name "NexusBot"
          git config user.email "bot@nexuseng.org"
          git add jobs/*.html
          git commit -m "🤖 Update job pages"
          git push
        continue-on-error: true  # avoids failing if no changes
